### ISSUE TITLE
Only attempt to add labels if a non-empty array of `labels` are defined

### ISSUE THREAD

**Issue by bdice** [ajschmidt8/r3#31]
I don't have privileges to add labels to many RAPIDS repos. I get errors, but I left `labels:` as an empty array. The label step should be skipped if no labels are defined, to conserve API calls and prevent errors.
```
Opening PRs:
https://github.com/rapidsai/cugraph/pull/3128
Error addings labels to "cugraph" PR: POST https://api.github.com/repos/rapidsai/cugraph/issues/3128/labels: 403 Must have admin rights to Repository. []
https://github.com/rapidsai/cugraph-ops/pull/323
Error addings labels to "cugraph-ops" PR: POST https://api.github.com/repos/rapidsai/cugraph-ops/issues/323/labels: 403 Must have admin rights to Repository. []
```

**Comment by ajschmidt8** [comment]
Fixed in https://github.com/ajschmidt8/r3/commit/800ea8446a7b6c4bb1420f0c36ecfc60548672b9.

Cutting a new release now.

**Comment by ajschmidt8** [comment]
New release is published. Closing.

https://github.com/ajschmidt8/r3/releases/tag/v0.1.5
